
import { Comic_Neue } from "next/font/google";
import  "@/app/globals.css"
import ThemeProvider, { ThemeContext } from "@/app/theme-provider";
import { useContext } from "react";
import BurguerButton from '@/elements/BurguerButton/BurguerButton'
import Sidebar from '@/components/Layout/Sidebar/Sidebar'
import DarkScreen from '@/components/Layout/DartkScreen/DarkScreen'
import { Header } from '@/elements/Header/Header'
import Footer from "@/components/Layout/Footer/Footer"

const comicNeue = Comic_Neue({
  subsets: ["latin"],
  weight: ['300','400','700'],
});

export const metadata = {
  title: "Biblioteams",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link 
          rel="icon"
          type="image/svg"
          href="/logo-robot.svg"
          sizes="16*16"
        />
      </head>
      <body className={comicNeue.className}>
        <ThemeProvider>
        <BurguerButton />
        <Sidebar />
        <Header/>
        <DarkScreen />     
          {children}
        <Footer/>
      </ThemeProvider>
      </body>
    </html>
  );
}
